[package]
name = "gguf-info"
version = "0.1.5"
edition = "2024"
description = "CLI tool to inspect and extract metadata from GGUF language model files."

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
gguf-rs = "0.1.4"
memmap2 = "0.9.5"
serde_json = "1.0.140"
